import {
  symRoundedAltRoute,
  symRoundedArrowBack,
  symRoundedArrowForward,
  symRoundedBlock,
  symRoundedBookmark,
  symRoundedBuild,
  symRoundedCallMerge,
  symRoundedCheck,
  symRoundedClose,
  symRoundedCloudUpload,
  symRoundedCompareArrows,
  symRoundedComputer,
  symRoundedDelete,
  symRoundedDevices,
  symRoundedDifference,
  symRoundedDoneAll,
  symRoundedDownload,
  symRoundedDriveFileRename,
  symRoundedEdit,
  symRoundedEditNote,
  symRoundedError,
  symRoundedFolderZip,
  symRoundedFormatInkHighlighter,
  symRoundedFormatListNumbered,
  symRoundedInfo,
  symRoundedJoin,
  symRoundedKeyboardArrowDown,
  symRoundedLabel,
  symRoundedLock,
  symRoundedMenuBook,
  symRoundedMobile,
  symRoundedMoreHoriz,
  symRoundedPermMedia,
  symRoundedPlaylistPlay,
  symRoundedQueueMusic,
  symRoundedRefresh,
  symRoundedReport,
  symRoundedRestartAlt,
  symRoundedStickyNote2,
  symRoundedSwapVert,
  symRoundedTabletMac,
  symRoundedTaskAlt,
  symRoundedTune,
  symRoundedUnfoldLess,
  symRoundedUnfoldMore,
  symRoundedUploadFile,
  symRoundedVisibilityOff,
  symRoundedWarning,
} from '@quasar/extras/material-symbols-rounded';

/** Tree-shaken SVG icons (Material Symbols Rounded) — only these glyphs ship in the bundle. */
export const I = {
  altRoute: symRoundedAltRoute,
  arrowBack: symRoundedArrowBack,
  arrowForward: symRoundedArrowForward,
  block: symRoundedBlock,
  bookmark: symRoundedBookmark,
  build: symRoundedBuild,
  callMerge: symRoundedCallMerge,
  check: symRoundedCheck,
  close: symRoundedClose,
  cloudUpload: symRoundedCloudUpload,
  compareArrows: symRoundedCompareArrows,
  computer: symRoundedComputer,
  delete: symRoundedDelete,
  devices: symRoundedDevices,
  difference: symRoundedDifference,
  doneAll: symRoundedDoneAll,
  download: symRoundedDownload,
  driveFileRename: symRoundedDriveFileRename,
  edit: symRoundedEdit,
  editNote: symRoundedEditNote,
  error: symRoundedError,
  folderZip: symRoundedFolderZip,
  formatInkHighlighter: symRoundedFormatInkHighlighter,
  formatListNumbered: symRoundedFormatListNumbered,
  info: symRoundedInfo,
  join: symRoundedJoin,
  keyboardArrowDown: symRoundedKeyboardArrowDown,
  label: symRoundedLabel,
  lock: symRoundedLock,
  menuBook: symRoundedMenuBook,
  mobile: symRoundedMobile,
  moreHoriz: symRoundedMoreHoriz,
  permMedia: symRoundedPermMedia,
  playlistPlay: symRoundedPlaylistPlay,
  queueMusic: symRoundedQueueMusic,
  refresh: symRoundedRefresh,
  report: symRoundedReport,
  restartAlt: symRoundedRestartAlt,
  stickyNote2: symRoundedStickyNote2,
  swapVert: symRoundedSwapVert,
  tabletMac: symRoundedTabletMac,
  taskAlt: symRoundedTaskAlt,
  tune: symRoundedTune,
  unfoldLess: symRoundedUnfoldLess,
  unfoldMore: symRoundedUnfoldMore,
  uploadFile: symRoundedUploadFile,
  visibilityOff: symRoundedVisibilityOff,
  warning: symRoundedWarning,
} as const;
